apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bmt-network-policy
  namespace: bmt-prod
spec:
  podSelector:
    matchLabels:
      app: bmt-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bmt-web
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    # Allow egress to DNS
    - ports:
      - protocol: UDP
        port: 53
