-- Create Table: campaign_insights
CREATE TABLE "campaign_insights" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "workspace_id" UUID NOT NULL,
    "campaign_id" UUID NOT NULL,
    "facebook_object_id" VARCHAR NOT NULL,
    "provider" VARCHAR NOT NULL DEFAULT 'meta',
    "date" DATE NOT NULL,
    "impressions" INT NOT NULL DEFAULT 0,
    "reach" INT NOT NULL DEFAULT 0,
    "frequency" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "clicks" INT NOT NULL DEFAULT 0,
    "unique_clicks" INT NOT NULL DEFAULT 0,
    "inline_link_clicks" INT NOT NULL DEFAULT 0,
    "ctr" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "cpc" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "cpm" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "spend" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "purchase" INT NOT NULL DEFAULT 0,
    "purchase_value" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "add_to_cart" INT NOT NULL DEFAULT 0,
    "initiated_checkout" INT NOT NULL DEFAULT 0,
    "landing_page_views" INT NOT NULL DEFAULT 0,
    "video_views" INT NOT NULL DEFAULT 0,
    "video_25" INT NOT NULL DEFAULT 0,
    "video_50" INT NOT NULL DEFAULT 0,
    "video_75" INT NOT NULL DEFAULT 0,
    "video_95" INT NOT NULL DEFAULT 0,
    "video_100" INT NOT NULL DEFAULT 0,
    "engagement" INT NOT NULL DEFAULT 0,
    "comments" INT NOT NULL DEFAULT 0,
    "likes" INT NOT NULL DEFAULT 0,
    "shares" INT NOT NULL DEFAULT 0,
    "saves" INT NOT NULL DEFAULT 0,
    "raw_payload" JSONB NOT NULL,
    "synced_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "pk_campaign_insights" PRIMARY KEY ("id"),
    CONSTRAINT "fk_campaign_insights_workspaces_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_campaign_insights_campaigns_campaign_id" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id") ON DELETE CASCADE,
    CONSTRAINT "uq_campaign_insights_workspace_object_date_provider" UNIQUE ("workspace_id", "facebook_object_id", "date", "provider")
);

-- Create Table: ad_set_insights
CREATE TABLE "ad_set_insights" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "workspace_id" UUID NOT NULL,
    "ad_set_id" UUID NOT NULL,
    "facebook_object_id" VARCHAR NOT NULL,
    "provider" VARCHAR NOT NULL DEFAULT 'meta',
    "date" DATE NOT NULL,
    "impressions" INT NOT NULL DEFAULT 0,
    "reach" INT NOT NULL DEFAULT 0,
    "frequency" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "clicks" INT NOT NULL DEFAULT 0,
    "unique_clicks" INT NOT NULL DEFAULT 0,
    "inline_link_clicks" INT NOT NULL DEFAULT 0,
    "ctr" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "cpc" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "cpm" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "spend" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "purchase" INT NOT NULL DEFAULT 0,
    "purchase_value" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "add_to_cart" INT NOT NULL DEFAULT 0,
    "initiated_checkout" INT NOT NULL DEFAULT 0,
    "landing_page_views" INT NOT NULL DEFAULT 0,
    "video_views" INT NOT NULL DEFAULT 0,
    "video_25" INT NOT NULL DEFAULT 0,
    "video_50" INT NOT NULL DEFAULT 0,
    "video_75" INT NOT NULL DEFAULT 0,
    "video_95" INT NOT NULL DEFAULT 0,
    "video_100" INT NOT NULL DEFAULT 0,
    "engagement" INT NOT NULL DEFAULT 0,
    "comments" INT NOT NULL DEFAULT 0,
    "likes" INT NOT NULL DEFAULT 0,
    "shares" INT NOT NULL DEFAULT 0,
    "saves" INT NOT NULL DEFAULT 0,
    "raw_payload" JSONB NOT NULL,
    "synced_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "pk_ad_set_insights" PRIMARY KEY ("id"),
    CONSTRAINT "fk_ad_set_insights_workspaces_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_ad_set_insights_adsets_ad_set_id" FOREIGN KEY ("ad_set_id") REFERENCES "adsets"("id") ON DELETE CASCADE,
    CONSTRAINT "uq_ad_set_insights_workspace_object_date_provider" UNIQUE ("workspace_id", "facebook_object_id", "date", "provider")
);

-- Create Table: ad_insights
CREATE TABLE "ad_insights" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "workspace_id" UUID NOT NULL,
    "ad_id" UUID NOT NULL,
    "facebook_object_id" VARCHAR NOT NULL,
    "provider" VARCHAR NOT NULL DEFAULT 'meta',
    "date" DATE NOT NULL,
    "impressions" INT NOT NULL DEFAULT 0,
    "reach" INT NOT NULL DEFAULT 0,
    "frequency" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "clicks" INT NOT NULL DEFAULT 0,
    "unique_clicks" INT NOT NULL DEFAULT 0,
    "inline_link_clicks" INT NOT NULL DEFAULT 0,
    "ctr" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "cpc" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "cpm" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "spend" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "purchase" INT NOT NULL DEFAULT 0,
    "purchase_value" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "add_to_cart" INT NOT NULL DEFAULT 0,
    "initiated_checkout" INT NOT NULL DEFAULT 0,
    "landing_page_views" INT NOT NULL DEFAULT 0,
    "video_views" INT NOT NULL DEFAULT 0,
    "video_25" INT NOT NULL DEFAULT 0,
    "video_50" INT NOT NULL DEFAULT 0,
    "video_75" INT NOT NULL DEFAULT 0,
    "video_95" INT NOT NULL DEFAULT 0,
    "video_100" INT NOT NULL DEFAULT 0,
    "engagement" INT NOT NULL DEFAULT 0,
    "comments" INT NOT NULL DEFAULT 0,
    "likes" INT NOT NULL DEFAULT 0,
    "shares" INT NOT NULL DEFAULT 0,
    "saves" INT NOT NULL DEFAULT 0,
    "raw_payload" JSONB NOT NULL,
    "synced_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "pk_ad_insights" PRIMARY KEY ("id"),
    CONSTRAINT "fk_ad_insights_workspaces_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_ad_insights_ads_ad_id" FOREIGN KEY ("ad_id") REFERENCES "ads"("id") ON DELETE CASCADE,
    CONSTRAINT "uq_ad_insights_workspace_object_date_provider" UNIQUE ("workspace_id", "facebook_object_id", "date", "provider")
);

-- Create Table: insight_sync_histories
CREATE TABLE "insight_sync_histories" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "workspace_id" UUID NOT NULL,
    "status" VARCHAR NOT NULL DEFAULT 'RUNNING',
    "started_at" TIMESTAMPTZ NOT NULL,
    "finished_at" TIMESTAMPTZ,
    "records_processed" INT NOT NULL DEFAULT 0,
    "records_created" INT NOT NULL DEFAULT 0,
    "records_updated" INT NOT NULL DEFAULT 0,
    "duration" INT,
    "error_message" VARCHAR,

    CONSTRAINT "pk_insight_sync_histories" PRIMARY KEY ("id"),
    CONSTRAINT "fk_insight_sync_histories_workspaces_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE
);
