export declare const AUTH_SERVICE_TOKEN = "AUTH_SERVICE_TOKEN";
export declare const AUTH_STRATEGY_TOKEN = "AUTH_STRATEGY_TOKEN";
export declare const CURRENT_USER_EXTRACTOR_TOKEN = "CURRENT_USER_EXTRACTOR_TOKEN";
