"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdCreativeResponseDto = exports.UpdateAdCreativeDto = exports.CreateAdCreativeDto = void 0;
class CreateAdCreativeDto {
    campaignId;
    creativeType;
    name;
    primaryText;
    headline;
    description;
    callToAction;
    destinationUrl;
    displayLink;
    caption;
    linkDescription;
    facebookPageId;
    instagramAccountId;
    mediaType;
    mediaAssetId;
    thumbnailAssetId;
    pixelId;
    trackingParameters;
    creativeSpec;
    labels;
    tags;
}
exports.CreateAdCreativeDto = CreateAdCreativeDto;
class UpdateAdCreativeDto {
    name;
    creativeType;
    primaryText;
    headline;
    description;
    callToAction;
    destinationUrl;
    displayLink;
    caption;
    linkDescription;
    facebookPageId;
    instagramAccountId;
    mediaType;
    mediaAssetId;
    thumbnailAssetId;
    pixelId;
    trackingParameters;
    creativeSpec;
    status;
    labels;
    tags;
}
exports.UpdateAdCreativeDto = UpdateAdCreativeDto;
class AdCreativeResponseDto {
    id;
    campaignId;
    creativeType;
    name;
    primaryText;
    headline;
    description;
    callToAction;
    destinationUrl;
    displayLink;
    caption;
    linkDescription;
    facebookPageId;
    instagramAccountId;
    mediaType;
    mediaAssetId;
    thumbnailAssetId;
    pixelId;
    trackingParameters;
    creativeSpec;
    status;
    draftVersion;
    externalCreativeId;
    publishedAt;
    createdBy;
    updatedBy;
    createdAt;
    updatedAt;
    labels;
    tags;
}
exports.AdCreativeResponseDto = AdCreativeResponseDto;
//# sourceMappingURL=adcreative.dto.js.map