import { MetaAuthService } from '../application/services/meta-auth.service';
import { MetaAssetSyncService } from '../application/services/meta-asset-sync.service';
import { MetaBusinessService } from '../application/services/meta-business.service';
import { MetaPageService } from '../application/services/meta-page.service';
import { MetaAdAccountService } from '../application/services/meta-ad-account.service';
import { MetaInstagramService } from '../application/services/meta-instagram.service';
import { MetaPixelService } from '../application/services/meta-pixel.service';
import { MetaCatalogService } from '../application/services/meta-catalog.service';
import { MetaRelationshipSyncService } from '../application/services/meta-relationship-sync.service';
import { MetaBusinessRelationshipService } from '../application/services/meta-business-relationship.service';
import { MetaPageRelationshipService } from '../application/services/meta-page-relationship.service';
import { MetaAdAccountRelationshipService } from '../application/services/meta-ad-account-relationship.service';
import { ConnectResponseDto, CallbackResponseDto, ConnectionStatusDto, DisconnectResponseDto } from '../common/meta-auth.dto';
export declare class MetaAuthController {
    private readonly metaAuthService;
    private readonly syncService;
    private readonly businessService;
    private readonly pageService;
    private readonly adAccountService;
    private readonly instagramService;
    private readonly pixelService;
    private readonly catalogService;
    private readonly relSyncService;
    private readonly businessRelService;
    private readonly pageRelService;
    private readonly adAccountRelService;
    constructor(metaAuthService: MetaAuthService, syncService: MetaAssetSyncService, businessService: MetaBusinessService, pageService: MetaPageService, adAccountService: MetaAdAccountService, instagramService: MetaInstagramService, pixelService: MetaPixelService, catalogService: MetaCatalogService, relSyncService: MetaRelationshipSyncService, businessRelService: MetaBusinessRelationshipService, pageRelService: MetaPageRelationshipService, adAccountRelService: MetaAdAccountRelationshipService);
    connect(req: any): Promise<ConnectResponseDto>;
    callback(code: string, state: string, req: any): Promise<CallbackResponseDto>;
    disconnect(req: any): Promise<DisconnectResponseDto>;
    status(req: any): Promise<ConnectionStatusDto>;
    sync(req: any): Promise<any>;
    getBusinesses(req: any): Promise<any[]>;
    getPages(req: any): Promise<any[]>;
    getAdAccounts(req: any): Promise<any[]>;
    getInstagram(req: any): Promise<any[]>;
    getPixels(req: any): Promise<any[]>;
    getCatalogs(req: any): Promise<any[]>;
    syncRelationships(req: any): Promise<any>;
    getBusinessRelationships(req: any): Promise<any[]>;
    getPageRelationships(req: any): Promise<any[]>;
    getAdAccountRelationships(req: any): Promise<any[]>;
}
